### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by oeyYoung** [miccunifi/QualiCLIP#2]
Can you make the code public? I'm working on IQA, and there are very few papers to refer to, and the disclosure of your code will be very helpful to my studies.

**Comment by LorenzoAgnolucci** [comment]
Hi @oeyYoung!

Thanks for your interest in our work! I am planning to release the pre-trained model and the inference code very soon (a couple of weeks max), but we will release the training code only upon acceptance.

But since you are interested in IQA, take a look at our [other work](https://github.com/miccunifi/ARNIQA), which is completely public.

**Comment by oeyYoung** [comment]
Thank you for your recommendation! I look forward to your update(..＞◡＜..)

**Comment by LorenzoAgnolucci** [comment]
Hi @oeyYoung,

sorry if it took longer than expected but the pre-trained model and the inference code are now public!
